apiVersion: v1
kind: Pod
metadata:
  name: secret-manager-demo
  labels:
    purpose: secret-manager-demo
spec:
  serviceAccountName: secret-manager-demo-svc
  containers:
  - name: secret-manager-demo
    image: google/cloud-sdk:365.0.1
    command: ["/bin/sh","-c"]
    args: ["echo $(gcloud secrets versions access latest --secret='my-secret') && sleep infinity"]
  restartPolicy: OnFailure
